export const USER_ORDERS_LIST_CONNECTION_OPEN: 'USER_ORDERS_LIST_CONNECTION_OPEN' = 'USER_ORDERS_LIST_CONNECTION_OPEN';
export const USER_ORDERS_LIST_CONNECTION_CLOSE: 'USER_ORDERS_LIST_CONNECTION_CLOSE' = 'USER_ORDERS_LIST_CONNECTION_CLOSE';
export const USER_ORDERS_LIST_CONNECTION_SUCCESS: 'USER_ORDERS_LIST_CONNECTION_SUCCESS' = 'USER_ORDERS_LIST_CONNECTION_SUCCESS';
export const USER_ORDERS_LIST_CONNECTION_ERROR: 'USER_ORDERS_LIST_CONNECTION_ERROR' = 'USER_ORDERS_LIST_CONNECTION_ERROR';
export const USER_ORDERS_LIST_CONNECTION_CLOSED: 'USER_ORDERS_LIST_CONNECTION_CLOSED' = 'USER_ORDERS_LIST_CONNECTION_CLOSED';
export const USER_ORDERS_LIST_RECEIVED: 'USER_ORDERS_LIST_RECEIVED' = 'USER_ORDERS_LIST_RECEIVED';
